server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: zjl792644
  application:
    name: item-service
  rabbitmq:  #消息队列的相关配置
    host: 192.168.85.10 #rabbitmq所在的ip地址
    username: root
    password: zjl792644
    virtual-host: /root   #虚拟路径
    template:      #有关AmqpTemplate的配置
      retry:       #失败重试
        enabled: true    #开启失败重试
        initial-interval: 10000ms    #第一次重试的间隔时长
        max-interval: 300000ms       #最长重试间隔时长
        multiplier: 2                #下次重试间隔的倍数
      exchange: ly.item.exchange     #默认的交换机名称
    publisher-confirms: true         #生产者确认机制，确保消息会正确发送，如果失败会触发重试机制

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.item.pojo